name: Deploy on CentOS
runs:
  using: composite
  steps:
    - name: Build project
      shell: bash
      run: |

        mkdir -p $HOME/.m2
        echo "<settings>" > $HOME/.m2/settings.xml
        echo "<mirrors><mirror><id>google-maven-central</id><name>GCS Maven Central mirror</name><url>https://maven-central.storage-download.googleapis.com/maven2/</url><mirrorOf>central</mirrorOf></mirror></mirrors>" >> $HOME/.m2/settings.xml
        echo "<servers><server><id>sonatype-nexus-snapshots</id><username>$CI_DEPLOY_USERNAME</username><password>$CI_DEPLOY_PASSWORD</password></server><server><id>sonatype-nexus-staging</id><username>$CI_DEPLOY_USERNAME</username><password>$CI_DEPLOY_PASSWORD</password></server></servers>" >> $HOME/.m2/settings.xml
        echo "</settings>" >> $HOME/.m2/settings.xml
        
        pwd
