name: Deploy on CentOS
runs:
  using: composite
  steps:
    - name: Build project
      shell: bash
      run: |
        source scl_source enable $SCL_ENABLE || true
        git --version
        gcc --version
        cmake --version
        gradle --version
        mvn -version
        gpg --version
        python3 --version
        df -h

        export MAKEJ=$(getconf _NPROCESSORS_ONLN)
        echo Fetching $GITHUB_REPOSITORY@$GITHUB_SHA
        git init
        git fetch --depth 1 https://github.com/$GITHUB_REPOSITORY $GITHUB_SHA
        git checkout $GITHUB_SHA
        git submodule update --init --recursive
        git submodule foreach --recursive 'git reset --hard'

        echo "Fixing HOME to /root (was '$HOME')"
        export HOME=/root

