name: pytorch
on:
  push:
    paths:
      - pytorch/**
  pull_request:
    paths:
      - pytorch/**
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_CUDA: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04
    container: centos:7
#    strategy:
#      matrix:
#        ext: ["", -gpu]
    steps:
      - uses: carloscj18/javacpp-presets/.github/actions/deploy-centos-part1@actions
      - uses: carloscj18/javacpp-presets/.github/actions/deploy-centos-part2@actions
      - uses: carloscj18/javacpp-presets/.github/actions/deploy-centos-part3@actions
      - uses: carloscj18/javacpp-presets/.github/actions/deploy-centos-part4@actions
      - uses: carloscj18/javacpp-presets/.github/actions/deploy-centos-part5@actions
      - uses: carloscj18/javacpp-presets/.github/actions/deploy-centos-part6@actions
  redeploy:
    needs: [linux-x86_64]
    runs-on: ubuntu-18.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
